Doubles/Doubles/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

urlpatterns = [
    url(r'', include('matching.urls')),
    url(r'', include('waiting.urls')),
    url(r'^admin/', admin.site.urls),
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/templates/', 'matching/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

Doubles/matching/urls.py
from django.conf.urls import url
from . import views

app_name = 'matching'

urlpatterns = [
    url(r'^map$', views.map, name='map'),
    url(r'^home$', views.home, name='home'),
    url(r'^search$', views.search, name='search'),
    url(r'^login$', views.login, name='login'),
    url(r'^execute_matching$', views.execute_matching, name='execute_matching'),
    url(r'^login_auth$', views.login_auth, name='login_auth'),
    url(r'^register$', views.register, name='register'),
    url(r'^regist_query$', views.regist_query, name='regist_query'),
    url(r'^register_auth$', views.register_auth, name='register_auth'),
    url(r'^matched_but_still_meet$', views.matched_but_still_meet, name='matched_but_still_meet'),
    url(r'^meat_but_still_eval$', views.meat_but_still_eval, name='meat_but_still_eval'),
    ]

Doubles/matching/views.py
from django.shortcuts import render
import json
import urllib.request
import urllib
import requests
import os.path
import numpy as np
import urllib.parse
import datetime

lat = 35.462286
long = 139.632353

userid = "line:U89bd9c76f03831c659c6848bf1d12fb0"
text = "マッチングしました！ おめでとうございます！"


def sendLine(userid, text):

 p = 'curl -X POST https://studio.twilio.com/v1/Flows/FW0983b8518646aa854799eccf18807c39/Executions -d To='+userid+' -d From=line:1619535250  -d Parameters={\\"text\\":\\"'+text+'\\"}  -u ACd90d602dd72e199e7d5e4de72cdfd14a:fe5ca9c7a8c3ab7a307c692087693af0'
 req = os.system(p)

#緯度経度をもとに最寄駅のコードを取得する
def getCode(lat, long):
    key = "eBBWPyXMYduCN759"
    url = "http://api.ekispert.jp/v1/json/geo/station?key="+key+"&geoPoint="+str(lat)+","+str(long)+",tokyo,10000&type=train&stationCount=1"
    result = requests.get(url)
    data = result.json()
    return str(data["ResultSet"]["Point"]["Station"]["code"])

new_code = getCode(lat,long)

#現在のリクエストマスタを取得する
def get_requestData():
    url = 'https://itto-ki.cybozu.com/k/v1/records.json?app=9'
    headers = {'X-Cybozu-API-Token': 'tjNhIJmlfeLfKrdN86eN3hv0dGRPxkSsdzrg3Wks'}
    res = requests.get(url ,headers=headers)
    return  res.json()["records"]


#対象ユーザの最寄駅コードと許容時間を渡して，共通の駅を取得する
def get_commonStation(bl, um):
    url = "http://api.ekispert.jp/v1/json/search/multipleRange?key=eBBWPyXMYduCN759&baseList="+bl+"&upperMinute="+um+"&limit=1"
    r = requests.get(url)
    return r.json()



##評価待ちマスタへの書き込み
def write_validation(waiting_data, i, x):
        sendLine(userid,text)
        userID=waiting_data[i]["userID"]["value"]

        s = 'id=\"' + userID +  '\"'

        s_quote = urllib.parse.quote(s)

        url = 'https://itto-ki.cybozu.com/k/v1/records.json?app=8&query='+s_quote

        # +'&password='+password
    # headers = {
    #     'Content-Type': 'application/json',
    #     'X-Cybozu-API-Token': 'RY6pqwdXsLotz6ZCQ7PR1r2BLuepTOA23BqDUkP4'
    # }
        headers = {
            'X-Cybozu-API-Token': 'RY6pqwdXsLotz6ZCQ7PR1r2BLuepTOA23BqDUkP4',
            # 'Content-Type': 'application/json'
            }

        res = requests.get(url ,headers=headers)
        data = res.json()
        # print(data["records"][0])
        # data = dict(res)
        # print(data)
        # data = json.dumps(str(data["records"])[1:][:-1])
        # data = json.dumps(data)
        if len(data["records"])==1:
            line_id = data["records"][0]["line"]["value"]
            print(line_id)
            s = 'line=\"' + line_id +  '\"'
            s_quote = urllib.parse.quote(s)
            url = 'https://itto-ki.cybozu.com/k/v1/records.json?app=12&query='+s_quote
            print(url)
            headers_line = {
                'X-Cybozu-API-Token': 'cFtON5Cef7yJSqMCTRDfIDGA6jvPqqieCbV5t6x9',
                # 'Content-Type': 'application/json'
                }
            res_line = requests.get(url ,headers=headers_line)
            data_line = res_line.json()
            if len(data_line["records"])==1:
                line_system_id = data_line["records"][0]["line_id_system"]["value"]
                sendLine(userid, text)
                print(line_system_id)
                print(userid)
                print("テキスト送信")
            # if len(data_line["records"])==1:
            #     print("hello")



        # print(data["line"]["value"])
        # print(data[1])
        # print(data["records"][0]["$id"]["value"])
        # print(data[0])



        url = 'https://itto-ki.cybozu.com/k/v1/record.json'
        headers = {'X-Cybozu-API-Token': '132Udy1Gp8xkMmk2u3U2P2mJxUhtTd2W0moGtNOo','Content-Type' : "application/json"}
        record = {
                    "app": "13",
                    "record": {
                        "userID": {
                            "value": waiting_data[i]["userID"]["value"]
                            },
                        "date": {
                            "value": waiting_data[i]["date"]["value"]
                            },
                        "start_time": {
                            "value": waiting_data[i]["start_time"]["value"]
                            },
                        "end_time": {
                            "value": waiting_data[i]["end_time"]["value"]
                            },
                        "station_name": {
                            "value": waiting_data[i]["station_name"]["value"]
                            },
                        "station_code": {
                            "value": waiting_data[i]["station_code"]["value"]
                            },
                        "range": {
                            "value": waiting_data[i]["range"]["value"]
                            },
                        "sex": {
                            "value": waiting_data[i]["sex"]["value"]
                            },
                        "partner":{
                            "value":waiting_data[x]["userID"]["value"]
                           },
                        "line":{
                            "value":waiting_data[i]["userID"]["value"]
                           }
                        }
                    }


        resp = requests.post(url, json=record, headers=headers)

        dct={"data": resp}
        # print("success")


#post_data:今回新たに申請してきたユーザー
#waiting_data:リクエストマスタに登録されている，　マッチングを待っているユーザー群
def compare():
    waiting_data = get_requestData()
    flag=0

    for i in range(1, len(waiting_data)):
        if(flag==1):break
        elif(waiting_data[0]["sex"]["value"] == waiting_data[i]["sex"]["value"]):
            bl = new_code + ":" + waiting_data[i]["station_code"]["value"]
            um = "180" +":"+ waiting_data[i]["range"]["value"]
            station = get_commonStation(bl, um)
            # print(station)
            if "Point" in station["ResultSet"]:
                    for j in range(len(waiting_data)):
                        if (waiting_data[0]["sex"]["value"] != waiting_data[j]["sex"]["value"] ):
                                bl2 = bl+":"+waiting_data[j]["station_code"]["value"]
                                um2 = um+":"+ waiting_data[j]["range"]["value"]
                                station=get_commonStation(bl2, um2)
                                if "Point" in station["ResultSet"]:


                                    for k in range(len(waiting_data)):
                                        if (waiting_data[0]["sex"]["value"] != waiting_data[k]["sex"]["value"] and k > j):
                                            bl3 = bl2+":"+waiting_data[k]["station_code"]["value"]
                                            um3 = um2 +":"+ waiting_data[k]["range"]["value"]
                                            station=get_commonStation(bl3, um3)
                                            if "Point" in station["ResultSet"]:

                                                ##jとkの性別が同じ
                                                if(np.random.rand() > 0.5):
                                                    write_validation(waiting_data, i, j)
                                                    write_validation(waiting_data, j, i)
                                                    write_validation(waiting_data, k, 0)
                                                    write_validation(waiting_data, 0, k)

                                                else :
                                                    write_validation(waiting_data, 0, j)
                                                    write_validation(waiting_data, j, 0)
                                                    write_validation(waiting_data, k, i)
                                                    write_validation(waiting_data, i, k)
                                                    # print(station[“ResultSet”][“Point”][“Station”][“Name”])
                                                flag = 1
                                                break
                                else:
                                    continue
                                break
            else:
                    # print("i:"+str(i)+":"+waiting_data[i]["sex"]["value"])
                    # print("miss match")

                    return "FAIL"
    # In[216]:







def getStation(lat, long):
   key = "eBBWPyXMYduCN759"
   url = "http://api.ekispert.jp/v1/json/geo/station?key="+key+"&geoPoint="+str(lat)+","+str(long)+",tokyo,10000&type=train&stationCount=1"
   result = requests.get(url)
   data = result.json()
   return data["ResultSet"]["Point"]["Station"]

def login(request):
    return render(request,'login.html')

def home(request):
    dct = {"session_name":request.session['name']}
    return render(request,'home.html',dct)

def search(request):
    dct = {"session_name":request.session['name']}
    return render(request,'home.html',dct)

def login_auth(request):


    line_id = request.POST['line_id']
    password = request.POST['password']

    s = 'password=\"' + password + '\"and line=\"'+ line_id + '\"'

    s_quote = urllib.parse.quote(s)

    url = 'https://itto-ki.cybozu.com/k/v1/records.json?app=8&query='+s_quote
    # +'&password='+password
# headers = {
#     'Content-Type': 'application/json',
#     'X-Cybozu-API-Token': 'RY6pqwdXsLotz6ZCQ7PR1r2BLuepTOA23BqDUkP4'
# }
    headers = {
        'X-Cybozu-API-Token': 'RY6pqwdXsLotz6ZCQ7PR1r2BLuepTOA23BqDUkP4'}

    res = requests.get(url ,headers=headers)

    data = res.json()
    print(len(data))

    if len(data["records"])!=1:
        return render(request,'login.html')
    else:
        request.session['userid'] = data["records"][0]["$id"]["value"]
        request.session['sex'] = data["records"][0]["sex"]["value"]
        request.session['name'] = data["records"][0]["name"]["value"]
        dct = {"session_name":request.session['name'],
               "session_sex":request.session['sex'],
               "session_userid" : request.session["userid"]

Doubles/matching/templates/after_match.html
{% load static %}

<head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>タイトル</title>

  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>
  <div class="container">
    <div class="center-block">
        <table border="1">
            <thead>
                <tr>
                    <th>場所</th>
                    <th>日時</th>
                    <th>気に入った！</th>
                </tr>
            </thead>
            <tbody>
                {% for record in records %}
                <tr>
                    <td>{{ record.station_name.value }}</td>
                    <td>{{ record.date.value }}  {{ record.start_time.value }}</td>
                    <td> 
                        <form action="">
                            <button class="btn btn-primary"> 承認 {{ record.partner.value }} </button>
                        </form>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
</body>

Doubles/matching/templates/friend_regist.html
{% load static %}

<head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>タイトル</title>

  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>
  <div class="container-fluid">
    <div class="container">
      <div class="card">
        <h5 class="card-header bg-primary text-white">{{session_name}} さん ようこそ</h5>
        <div class="card-body">
          <div class="center-block" align="center">
            <img src="{% static 'img/qr.png' %}">
            <hr>
            <a href="https://line.me/R/ti/p/0eYQZxgqOE">DoublesをLINEに登録</a>
          </div>
        </div>
        <div class="card-footer text-white">
          <a href="{% url 'matching:home' %}" class="btn btn-primary btn-lg btn-block" role="button" >ホーム画面へ</a>
        </div>
      </div>
    </div>
  </div>

</body>

</script>

Doubles/matching/templates/home.html
{% load static %}

<head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>タイトル</title>

  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>
  <div class="container-fluid">
    <div class="container">
      <div class="card">
        <h5 class="card-header bg-primary text-white">{{session_name}} さん ようこそ</h5>
        <div class="card-body">
          <div class="center-block">
            <a href="{% url 'matching:map' %}" class="btn btn-primary btn-lg btn-block" role="button" >待ち情報を登録</a>
            <a href="{% url 'matching:matched_but_still_meet' %}" class="btn btn-primary btn-lg btn-block" role="button" >まだ会っていない人</a>
            <a href="{% url 'matching:meat_but_still_eval' %}" class="btn btn-primary btn-lg btn-block" role="button" >既に会った人</a>

            </form>

          </div>
        </div>
        <div class="card-footer text-white"><a href="{% url 'matching:register' %}"></a></div>
      </div>
    </div>
  </div>

</body>

</script>

Doubles/matching/templates/login.html
{% load static %}

<head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>タイトル</title>

  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>
  <div class="container-fluid">
    <div class="container">
      <div class="card">
        <h5 class="card-header bg-primary text-white">ログイン情報</h5>
        <div class="card-body">
          <div class="center-block">
            <form action="{% url 'matching:login_auth' %}" method="post">
              {% csrf_token %}

              <label class="center-block">LINE ID</label>
              <input name="line_id" id="line_id" type="text" class="form-control" value="">

              <label class="center-block">パスワード</label>
              <input name="password" id="password" type="password" class="form-control" value="">

              <br>
              <button type="submit" class="btn btn-primary btn-lg btn-block">ログイン</button>
            </form>
          </div>
        </div>
        <div class="card-footer text-white"><a href="{% url 'matching:register' %}">新規会員登録</a></div>
      </div>
    </div>
  </div>

</body>

</script>

Doubles/matching/templates/map.html
{% load static %}

<head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>タイトル</title>

  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>
  <div class="row">
  <div id='map_canvas' class="col-sm-12" style="height:60%"></div>


  <div class="col-sm-12" align="center">
  <form action="{% url 'matching:regist_query' %}" method="post">
    {% csrf_token %}

    <label>日付</label>
    <input  name="input_date" id="input_date" type="date" class="form-control" value="2000-01-01">

    <div class="form-inline">

      <div>
        <label">開始時間</label>
        <input  name="input_start_time" id="input_start_time" type="time" class="form-control" value="00:00">
      </div>
      <div>
        <label">終了時間</label>
        <input  name="input_end_time" id="input_end_time" type="time" class="form-control" value="00:00">
      </div>

    </div>

    <label">移動可能許容時間</label>
    <input  name="available_time" id="available_time" type="number" class="form-control" value="0">


    <input type="hidden" name="input_lat" id="input_lat" value="0">
    <input type="hidden" name="input_lng" id="input_lng" value="0">
    <br>
    <button type="submit" class="btn btn-primary btn-lg btn-block">パートナーを待つ！</button>
    <!-- <input type="submit" class="btn btn-primary btn-block" value="Submit Button"> -->
 </form>
   </div>

</body>

<script type="text/javascript">
  var input_lat = document.getElementById("input_lat");
  var input_lng = document.getElementById("input_lng");
  // Geolocation APIに対応している
  // if (navigator.geolocation) {
  //   alert("この端末では位置情報が取得できます");
  // // Geolocation APIに対応していない
  // } else {
  //   alert("この端末では位置情報が取得できません");
  // }

  // 現在地取得処理
  function getPosition() {
    // 現在地を取得
    navigator.geolocation.getCurrentPosition(
      // 取得成功した場合
      function(position) {
        // alert("緯度:"+position.coords.latitude+",経度"+position.coords.longitude);
        current_lat = position.coords.latitude;
        current_lng = position.coords.longitude;
        map.setView([current_lat,current_lng], 15);
        input_lat.value = current_lat;
        input_lng.value = current_lng;

      },
      // 取得失敗した場合
      function(error) {
        switch (error.code) {
          case 1: //PERMISSION_DENIED
            alert("位置情報の利用が許可されていません");
            break;
          case 2: //POSITION_UNAVAILABLE
            alert("現在位置が取得できませんでした");
            break;
          case 3: //TIMEOUT
            alert("タイムアウトになりました");
            break;
          default:
            alert("その他のエラー(エラーコード:" + error.code + ")");
            break;
        }
      }
    );
  }
  data = {{data | safe}};
  data = data["records"]
  var click_position;

  // var bus_icon = L.icon({
  //     iconUrl: "{% static "img/bus_img/minato_bus_sample004.png" %}",
  //     iconRetinaUrl: "{% static "img/bus_img/minato_bus_sample004.png" %}",
  //     iconSize: [30, 30],
  //     iconAnchor: [15, 15],
  //     popupAnchor: [0, -14],
  // });
  var busstop_icon = L.icon({
    iconUrl: "{% static "img/tennis_pin.png" %}",
    iconRetinaUrl: "{% static "img/tennis_pin.png" %}",

    iconSize: [90, 90],
    iconAnchor: [50, 90],
    popupAnchor: [-5, -75],
  });
  // var update_time = 5000;
  // var center_lat = {{map_center_lat}}; //初期地図の中心点を定義
  // var center_lng = {{map_center_lng}}; //初期地図の中心点を定義
  // var marker = new Array();
  // var bus_list = new Array();
  // var distance_list = new Array();
  // var busStops = {{stops | safe}}
  // var route_id = {{route_id | safe}}
  // var selecting_ID;
  // var selecting_lat;
  // var selecting_lng;
  // var bus_marker_layer = new L.FeatureGroup();
  // //var busStops = {{stops | safe}}
  var tileLayer = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
  });
  // var baseLayers = {
  //     "OpenStreetMap": tileLayer
  // };
  var map = L.map('map_canvas', {
    zoomControl: true,
    // layers: [bus_marker_layer]
  });

  var popup = L.popup();

  function onMapClick(e) {
    click_position = e.latlng
    input_lat.value = click_position["lat"]
    input_lng.value = click_position["lng"]
    popup
        .setLatLng(e.latlng)
        .setContent("Clicked!")
        .openOn(map);
    //   }

    console.log(click_position)

  }

  map.on('click', onMapClick);
  // //車両の角度計算
  // function geoDirection(lat1, lng1, lat2, lng2) {
  //     var Y = Math.cos(lng2 * Math.PI / 180) * Math.sin(lat2 * Math.PI / 180 - lat1 * Math.PI / 180);
  //     var X = Math.cos(lng1 * Math.PI / 180) * Math.sin(lng2 * Math.PI / 180) - Math.sin(lng1 * Math.PI / 180) * Math.cos(lng2 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180 - lat1 * Math.PI / 180);
  //     var dirE0 = 180 * Math.atan2(Y, X) / Math.PI;
  //     if (dirE0 < 0) {
  //         dirE0 = dirE0 + 360;
  //     }
  //     var dirN0 = (dirE0 + 90) % 360;
  //     return dirN0;
  // }
  makemap();
  // L.control.scale().addTo(map);
  // //var stops = {{stops | safe}}
  // //console.log(stops)
  // $.getJSON("now_user",
  //     function(bus_data) {
  //         realtime_data = bus_data;
  //         console.log("data initialized!!!")
  //         set_bus_markers();
  //     });
  // function update() {
  //     $.getJSON("now_user",
  //         function(bus_data) {
  //             realtime_data = bus_data;
  //             console.log("data updated!!!")
  //         }
  //     );
  //     setTimeout(function() {
  //         update()
  //         update_bus_markers_position();
  //         //update_info()
  //         //make_distance_list();
  //     }, update_time);
  // }
  // update();
  // function update_bus_markers_position() {
  //     Object.keys(realtime_data).forEach(function(key) {
  //       if(realtime_data[key].bus_root==route_id){
  //         if(realtime_data[key].kmh>10){
  //           eval("busMarker" + realtime_data[key].bus + ".setRotationAngle(Math.ceil(geoDirection(Number(busMarker" + realtime_data[key].bus + "._latlng.lat),Number(busMarker" + realtime_data[key].bus +"._latlng.lng),Number(realtime_data[key].lat),Number(realtime_data[key].lng))));")
  //         }
  //         //緯度経度が0ならマーカー位置を更新しない
  //         if(realtime_data[key].lat != 0 && realtime_data[key].lng != 0){
  //           eval("busMarker" + realtime_data[key].bus + ".setLatLng([Number(realtime_data[key].lat),Number(realtime_data[key].lng)]).update();")
  //         }
  //       }
  //     });
  // }
  // function set_bus_markers() {
  //     Object.keys(realtime_data).forEach(function(key) {
  //       console.log(realtime_data[key].bus_root)
  //       if(realtime_data[key].bus_root==route_id){
  //         eval("busMarker" + realtime_data[key].bus + " = new L.marker([Number(realtime_data[key].lat), Number(realtime_data[key].lng)], {icon: bus_icon}).on('click', markerClick);")
  //         eval("busMarker" + realtime_data[key].bus + ".ID = realtime_data[key].bus")
  //         eval("bus_marker_layer.addLayer(busMarker" + realtime_data[key].bus + ")")
  //         eval("busMarker" + realtime_data[key].bus + ".bindPopup('<h4>'+realtime_data[key].bus+'</h4>')")
  //         //初期バスマーカーの角度を右向きに
  //         eval("busMarker" + realtime_data[key].bus + ".setRotationAngle(90)")
  //       }
  //     });
  // }
  // function markerClick(e) {
  //     var clicked_marker_latlng = this.getLatLng();
  //     map.setView([clicked_marker_latlng.lat, clicked_marker_latlng.lng]);
  //     selecting_ID = "bus_" + this.ID;
  //     //console.log('selecting_ID:' + selecting_ID)
  //     //alert("ID：" + this.ID + "を選択しました");
  // }
  // function get_nearest_busstop() {
  //     distance_list.length = 0;
  //     for (var i = 0; i < busStops.length; i++) {
  //         var dis = Math.abs(realtime_data[selecting_ID].lat - busStops[i].lat) + Math.abs(realtime_data[selecting_ID].lng - busStops[i].lng)
  //         distance_list.push(dis)
  //     }
  //     return busStops[distance_list.indexOf(Math.min.apply(null, distance_list))].name
  // }
  function makemap() {
    for (var i = 0; i < data.length; i++) {
      var busstopMarker = L.marker([data[i]["latitude"].value, data[i]["longitude"].value], {
        icon: busstop_icon
      });
      console.log("aa")
      busstopMarker.addTo(map);
      busstopMarker.bindPopup('<a href="http://www.kobe-minato.co.jp/ashi-syuku.html">' + data[i]["name"].value + '</a>');
    }
    map.setView([35.7945, 139.6579], 15);
    // getPosition()
    tileLayer.addTo(map);
  }
</script>

Doubles/matching/templates/register.html
{% load static %}

<head>
  <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>タイトル</title>

  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/leaflet.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/leaflet.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
</head>

<body>

  <div class="container-fluid">
    <div class="container">
      <div class="card">
        <h5 class="card-header bg-primary text-white">会員登録</h5>
        <div class="card-body">
          <div class="center-block">
            <form action="{% url 'matching:register_auth' %}" method="post">
              {% csrf_token %}

              <label class="center-block">名前</label>
              <input name="name" id="name" type="text" class="form-control" value="">

              <label class="center-block">カテゴリー</label>
              <select class="form-control" id="category" name="category">
                <option value="テニス" selected="selected">テニス</option>
                <option value="バドミントン" >バドミントン</option>
                <option value="卓球">卓球</option>
              </select>

              <label class="center-block">性別</label>
              <select class="form-control" id="sex" name="sex">
                <option value="男" selected="selected">男</option>
                <option value="女">女</option>
              </select>

              <label class="center-block">パスワード</label>
              <input name="password" id="password" type="password" class="form-control" value="">

              <label class="center-block">年齢</label>
              <input name="age" id="age" type="number" class="form-control" value="20">

              <label class="center-block">LINE ID</label>
              <input name="line_id" id="line_id" type="text" class="form-control" value="">
              <br>
              <button type="submit" class="btn btn-primary btn-lg btn-block">登録</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>

</script>